### ISSUE TITLE
Rescheduling/"Set Due Date" counts as reviews for some statistics, but not all

### ISSUE THREAD

**Issue by u2m4c6** [ankitects/anki#1160]
There seems to be a discrepancy in the backend with how rescheduled cards using the "Set Due Date" dialog in the browser are handled. 

Rescheduling cards counts as reviews for the stat "X cards/minute" but not for "Studied X cards in Y minutes today (Z seconds/card)". These cards ideally should not be counted in any statistics.

I am not familiar with Rust otherwise I would try to propose a pull request to fix this. It seems like the Python code involved with these dialogs just references the Rust backend. This might be an unavoidable bug due to how the "Set Due Date" function is currently implemented. Review stats are an important part of modifying settings for maximum efficiency, so I think this bug deserves attention/a redesign of rescheduling (if that is needed). This bug also ruins the very popular "heatmap" addon when "Set Due Date" is used.

**Comment by dae** [comment]
I believe the 'studied x cards' message has already been fixed in the current dev code - can you confirm? You'll need to report any add-on issues to the add-on author.

**Comment by u2m4c6** [comment]
I updated to 2.1.43 and the "X cards/minute" is still not correct after "Set Due Date" is run on a batch of cards. Anki counts the number of cards rescheduled as reps, which leads to crazy outputs like "52000 cards/minute". "Set Due Date" also messes up the standard Stats tab too (no addons involved).

The "Studied x cards in y minutes" is able to determine that "Set Due Date" cards should not be included, so I am wondering how we can add that functionality to "X cards/minute".

**Comment by dae** [comment]
I can't reproduce this using the current development code. Please confirm all add-ons are disabled, and then see if you can still trigger it with the latest code from git.

**Comment by u2m4c6** [comment]
I was also unable to reproduce it when all addons were disabled and using the latest code. Must have been an addon, I am not sure which one, but sounds like an issue that needs to be brought up to the various add-on creators, not an issue with the based Anki code (like you said from the beginning). Thanks for your help

**Comment by dae** [comment]
Thanks for confirming
