### ISSUE TITLE
Letter Keyboard Shortcuts not working after 2.1.50 on Telex keyboard (Vietnamese)

### ISSUE THREAD

**Issue by hai265** [ankitects/anki#2097]
On mac at least, and keyboard shortcuts using a single key (1, 2, 3, 4, e, etc) don't work while on the Telex keyboard. On 2.1.49 the shortcuts work however.

**Comment by dae** [comment]
Can you reproduce the issue with the latest beta? https://forums.ankiweb.net/t/anki-2-1-55-beta/23470

**Comment by hai265** [comment]
I was able to reproduce the issue on the latest beta: On telex the keyboard shortcuts don't work but work under English and Japanese.

**Comment by dae** [comment]
Beta 2 will likely bump the Qt version again, so it may be worth another try once it becomes available.

**Comment by hai265** [comment]
I downloaded 2.1.55 beta 5 and the shortcuts work again now.

**Comment by dae** [comment]
Thanks, glad to hear the issue's been addressed by Qt 6.4.

**Comment by wannli** [comment]
Still facing this issue, unfortunately. VNI (Vietnamese) keyboard with version 2.1.61.

**Comment by dae** [comment]
How does beta 1 fare? https://apps.ankiweb.net/downloads/beta/

**Comment by dae** [comment]
Dang. If may need a similar approach to https://github.com/ankitects/anki/pull/2533

**Comment by j-mesnil** [comment]
I looked a bit further into this issue and found the following behavior when using the in-built Telex keyboard of MacOS:

In the `_shortcutKeys` method in `qt/aqt/reviewer.py`, the shortcuts work if I define them using `Qt.Key` instead of with a string. E.g. `(Qt.Key.Key_Return, self.onEnterKey)` works, but `("e", self.mw.onEditCurrent)` doesn't work. However, the answer buttons 1, 2, 3, 4 are customizable by the user, and the `aqt.mw.pm.get_answer_key(ease)` call returns a string, not a `Qt.Key`.

So for fixing the non-customizable one-key short-cuts, it would suffice to change the strings to corresponding `Qt.Key`s. But I am not sure how to fix this for the customizable shortcuts without removing their customizability. Please let me know if you have some idea, I would be happy to try and fix this.


That being said, I have found that when using the third-party keyboard application https://evkeyvn.com/ instead of the built-in Telex keyboard, the shortcuts (including the customizable ones) work fine.

**Comment by dae** [comment]
Does Qt.Key.Key_1 work? If so, one possible solution here would be to detect when the answer keys are set to the default of 1/2/3/4, and switch the strings to those key values instead.

**Comment by j-mesnil** [comment]
I am sorry, I think I messed something up, I cannot reproduce the behavior I reported yesterday. The `Qt.Key.Key_Return` works for some reason even in the in-built Telex keyboard, but `Qt.Key.Key_1` or `Qt.Key.Key_E` do not work. So for the moment the only workaround I know using EVkey, it seems.

**Comment by rguan1** [comment]
Hi has this issue on the default macos telex keyboard been resolved? I believe I'm still facing the issue with the 1,2,3,4,r shortcuts when using the telex keyboard on version 23.12.1 and 24.06.2.

**Comment by rguan1** [comment]
I had some time to further investigate the issue today.

In [evenFilter(...)](https://github.com/ankitects/anki/blob/main/qt/aqt/main.py#L151) within main.py, I added this code and attached a debug point. It looks like both macOS telex & macOS U.S. both register keyboard presses correctly at least the lower-level call of eventFilter(...) as `Type.ShortcutOverride`. However, in Telex keyboard, that lower-level key press never triggers the QShortCut for "r", while in the US keyboard, it does. This seems to be related to the way that low-level event handlers `eventFilter(...)` behave versus higher-lvl event handlers `QShortCut` for keys that relate to Telex specific functionality. Hence why @j-mesnil and I didn't have an issue with `Qt.Key.Key_Return` on the Telex keyboard

The stupid solution would then seem to be to add the replay and other reviewer class shortcuts into the eventFilter, but that probably creates more problems than it solves (solves one keyboard but potentially duplicate shortcut signals for every other keyboard type). However, I think someone who might be more familiar with how QT UI handles different events might be able to think of a slicker solution?

```
def eventFilter(self, obj, evt):
         # Otherwise, handle our own events
        if handled := super().eventFilter(obj, evt):
            return handled
        
        if evt.type() == QEvent.Type.Shortcut or evt.type() == QEvent.Type.ShortcutOverride:
            print(evt.type())
            print(f"Key pressed: {evt.key()}")
            if evt.key() == Qt.Key.Key_R:
                # self.mw.reviewer.replayAudio()
                print("R key was pressed!")
```

**Comment by rguan1** [comment]
@bryanboateng 
I think the code fix might be a little complex as it relates to how QT handles key entry and how telex has special interactions for accent marks. In other words, I'm not familiar enough with QT  and keyboard to make a change that fixes this but breaks other languages potentially 

The workaround I ended on was just to remap the shortcut keys to F1, F2, F3, F4 which I believe do not have any accent marks interactions.
