### ISSUE TITLE
Various issues with MathJax editor

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2106]
https://forums.ankiweb.net/t/anki-2-1-55-beta-mathjax-preview/23529

**Comment by kleinerpirat** [comment]
I've pushed a fix in #2126 for newly added MathJax blocks rendering when preview is turned off.

**Comment by dae** [comment]
@pwintz could you clarify which of the reported issues are still there, and if possible break them up into individual tickets so they can be tracked separately?
