### ISSUE TITLE
Reverse text direction checkbox "breaks" basic navigation keyboard shortcuts like 

### ISSUE THREAD

**Issue by yarintm** [ankitects/anki#3484]
https://github.com/ankitects/anki/blob/407e2dc43b719f499d1d28f734e26620ce6a5fde/ftl/core/fields.ftl#L12

Reverse text direction checkbox in "fields"  is causing a bug- when editing a card with this setting checked, basic navigation keyboard shortcut like **command/option + arrows** not working

**Comment by abdnh** [comment]
This issue was fixed and came back a couple of times in the past. I can't reproduce it on the latest Anki (Windows) though.

**Comment by yarintm** [comment]
This issue is still present on Mac. I’d like to contribute and fix it myself—could someone guide me through the process?

**Comment by abdnh** [comment]
@yarintm Here's the existing fix: https://github.com/ankitects/anki/blob/e7e6a3834b72a682c1ae14b42f52c50bf89deb64/ts/editable/content-editable.ts#L150

Try tweaking it and see if that works.
